<a href="https://colab.research.google.com/github/elluis1001/deep-learning-challenge/blob/main/Starter_Code_02_21_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME':
# Create a DataFrame with the dropped columns:
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
count_type = application_df['APPLICATION_TYPE'].value_counts()
count_type

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(count_type[count_type < 528].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
count_type_class = application_df['CLASSIFICATION'].value_counts()
count_type_class

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
count_type_class_greater_1 = count_type_class[count_type_class > 1]
count_type_class_greater_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(count_type_class[count_type_class < 100].index)
classifications_to_replace
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1)
y = application_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])

hidden_nodes_1 = 7
hidden_nodes_2 = 14
hidden_nodes_3 = 21


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_1, activation = "relu", input_dim = number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 350

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 477 (1.86 KB)
Trainable params: 477 (1.86 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model by using the '.comple()' method
nn.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, validation_split = 01.5, epochs = 100)

Epoch 1/100
402/402 [==============================] - 3s 4ms/step - loss: 0.6465 - accuracy: 0.6427 - val_loss: 0.5826 - val_accuracy: 0.7086
Epoch 2/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5714 - accuracy: 0.7172 - val_loss: 0.5653 - val_accuracy: 0.7193
Epoch 3/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5588 - accuracy: 0.7242 - val_loss: 0.5617 - val_accuracy: 0.7284
Epoch 4/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5544 - accuracy: 0.7292 - val_loss: 0.5588 - val_accuracy: 0.7258
Epoch 5/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5513 - accuracy: 0.7306 - val_loss: 0.5574 - val_accuracy: 0.7255
Epoch 6/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5497 - accuracy: 0.7297 - val_loss: 0.5563 - val_accuracy: 0.7293
Epoch 7/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5482 - accuracy: 0.7318 - val_loss: 0.5564 - val_accuracy: 0.7283
Epoch 8/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5470 - accuracy: 0.7323 - val_loss: 0.5570 - val_accuracy: 0.7247
Epoch 9/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5464 - accuracy: 0.7303 - val_loss: 0.5560 - val_accuracy: 0.7283
Epoch 10/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5456 - accuracy: 0.7311 - val_loss: 0.5555 - val_accuracy: 0.7291
Epoch 11/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5452 - accuracy: 0.7318 - val_loss: 0.5575 - val_accuracy: 0.7260
Epoch 12/100
402/402 [==============================] - 2s 6ms/step - loss: 0.5446 - accuracy: 0.7329 - val_loss: 0.5564 - val_accuracy: 0.7293
Epoch 13/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5448 - accuracy: 0.7336 - val_loss: 0.5549 - val_accuracy: 0.7294
Epoch 14/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5437 - accuracy: 0.7339 - val_loss: 0.5549 - val_accuracy: 0.7290
Epoch 15/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5440 - accuracy: 0.7336 - val_loss: 0.5554 - val_accuracy: 0.7305
Epoch 16/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5432 - accuracy: 0.7346 - val_loss: 0.5558 - val_accuracy: 0.7298
Epoch 17/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5429 - accuracy: 0.7342 - val_loss: 0.5568 - val_accuracy: 0.7303
Epoch 18/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5427 - accuracy: 0.7343 - val_loss: 0.5571 - val_accuracy: 0.7305
Epoch 19/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5424 - accuracy: 0.7347 - val_loss: 0.5555 - val_accuracy: 0.7303
Epoch 20/100
402/402 [==============================] - 2s 5ms/step - loss: 0.5415 - accuracy: 0.7354 - val_loss: 0.5557 - val_accuracy: 0.7305
Epoch 21/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5419 - accuracy: 0.7355 - val_loss: 0.5562 - val_accuracy: 0.7295
Epoch 22/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5417 - accuracy: 0.7362 - val_loss: 0.5567 - val_accuracy: 0.7301
Epoch 23/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5414 - accuracy: 0.7353 - val_loss: 0.5568 - val_accuracy: 0.7301
Epoch 24/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5413 - accuracy: 0.7361 - val_loss: 0.5580 - val_accuracy: 0.7257
Epoch 25/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5413 - accuracy: 0.7371 - val_loss: 0.5567 - val_accuracy: 0.7304
Epoch 26/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5411 - accuracy: 0.7370 - val_loss: 0.5564 - val_accuracy: 0.7300
Epoch 27/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5408 - accuracy: 0.7371 - val_loss: 0.5563 - val_accuracy: 0.7302
Epoch 28/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5409 - accuracy: 0.7354 - val_loss: 0.5563 - val_accuracy: 0.7301
Epoch 29/100
402/402 [==============================] - 2s 6ms/step - loss: 0.5407 - accuracy: 0.7348 - val_loss: 0.5571 - val_accuracy: 0.7299
Epoch 30/100
402/402 [==============================] - 1s 4ms/step - loss: 0.5403 - accuracy: 0.7364 - val_loss: 0.5570 - val_accuracy: 0.7299
Epoch 31/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5403 - accuracy: 0.7360 - val_loss: 0.5572 - val_accuracy: 0.7294
Epoch 32/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5402 - accuracy: 0.7373 - val_loss: 0.5572 - val_accuracy: 0.7305
Epoch 33/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5403 - accuracy: 0.7354 - val_loss: 0.5568 - val_accuracy: 0.7298
Epoch 34/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5396 - accuracy: 0.7381 - val_loss: 0.5574 - val_accuracy: 0.7301
Epoch 35/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5395 - accuracy: 0.7374 - val_loss: 0.5575 - val_accuracy: 0.7302
Epoch 36/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5395 - accuracy: 0.7369 - val_loss: 0.5582 - val_accuracy: 0.7297
Epoch 37/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5396 - accuracy: 0.7369 - val_loss: 0.5574 - val_accuracy: 0.7304
Epoch 38/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5400 - accuracy: 0.7367 - val_loss: 0.5570 - val_accuracy: 0.7301
Epoch 39/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5394 - accuracy: 0.7374 - val_loss: 0.5568 - val_accuracy: 0.7303
Epoch 40/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5396 - accuracy: 0.7361 - val_loss: 0.5567 - val_accuracy: 0.7297
Epoch 41/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5390 - accuracy: 0.7375 - val_loss: 0.5567 - val_accuracy: 0.7302
Epoch 42/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5389 - accuracy: 0.7357 - val_loss: 0.5582 - val_accuracy: 0.7290
Epoch 43/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5388 - accuracy: 0.7385 - val_loss: 0.5579 - val_accuracy: 0.7303
Epoch 44/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5390 - accuracy: 0.7364 - val_loss: 0.5569 - val_accuracy: 0.7295
Epoch 45/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5383 - accuracy: 0.7360 - val_loss: 0.5588 - val_accuracy: 0.7298
Epoch 46/100
402/402 [==============================] - 2s 5ms/step - loss: 0.5388 - accuracy: 0.7370 - val_loss: 0.5581 - val_accuracy: 0.7297
Epoch 47/100
402/402 [==============================] - 1s 4ms/step - loss: 0.5385 - accuracy: 0.7373 - val_loss: 0.5579 - val_accuracy: 0.7289
Epoch 48/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5386 - accuracy: 0.7369 - val_loss: 0.5575 - val_accuracy: 0.7292
Epoch 49/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5385 - accuracy: 0.7380 - val_loss: 0.5589 - val_accuracy: 0.7299
Epoch 50/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5380 - accuracy: 0.7384 - val_loss: 0.5582 - val_accuracy: 0.7301
Epoch 51/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5382 - accuracy: 0.7370 - val_loss: 0.5599 - val_accuracy: 0.7287
Epoch 52/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5382 - accuracy: 0.7371 - val_loss: 0.5582 - val_accuracy: 0.7302
Epoch 53/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5382 - accuracy: 0.7378 - val_loss: 0.5579 - val_accuracy: 0.7298
Epoch 54/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5379 - accuracy: 0.7382 - val_loss: 0.5590 - val_accuracy: 0.7291
Epoch 55/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5380 - accuracy: 0.7367 - val_loss: 0.5586 - val_accuracy: 0.7269
Epoch 56/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5378 - accuracy: 0.7374 - val_loss: 0.5589 - val_accuracy: 0.7283
Epoch 57/100
402/402 [==============================] - 1s 4ms/step - loss: 0.5378 - accuracy: 0.7381 - val_loss: 0.5586 - val_accuracy: 0.7293
Epoch 58/100
402/402 [==============================] - 2s 6ms/step - loss: 0.5379 - accuracy: 0.7379 - val_loss: 0.5579 - val_accuracy: 0.7278
Epoch 59/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5379 - accuracy: 0.7374 - val_loss: 0.5581 - val_accuracy: 0.7294
Epoch 60/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5377 - accuracy: 0.7371 - val_loss: 0.5593 - val_accuracy: 0.7298
Epoch 61/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5377 - accuracy: 0.7372 - val_loss: 0.5577 - val_accuracy: 0.7286
Epoch 62/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5370 - accuracy: 0.7378 - val_loss: 0.5583 - val_accuracy: 0.7290
Epoch 63/100
402/402 [==============================] - 2s 5ms/step - loss: 0.5375 - accuracy: 0.7363 - val_loss: 0.5579 - val_accuracy: 0.7297
Epoch 64/100
402/402 [==============================] - 1s 4ms/step - loss: 0.5372 - accuracy: 0.7387 - val_loss: 0.5585 - val_accuracy: 0.7290
Epoch 65/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5368 - accuracy: 0.7362 - val_loss: 0.5591 - val_accuracy: 0.7258
Epoch 66/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5372 - accuracy: 0.7371 - val_loss: 0.5588 - val_accuracy: 0.7276
Epoch 67/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5367 - accuracy: 0.7387 - val_loss: 0.5585 - val_accuracy: 0.7289
Epoch 68/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5365 - accuracy: 0.7371 - val_loss: 0.5585 - val_accuracy: 0.7286
Epoch 69/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5367 - accuracy: 0.7372 - val_loss: 0.5580 - val_accuracy: 0.7289
Epoch 70/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5366 - accuracy: 0.7375 - val_loss: 0.5584 - val_accuracy: 0.7295
Epoch 71/100
402/402 [==============================] - 1s 4ms/step - loss: 0.5363 - accuracy: 0.7394 - val_loss: 0.5602 - val_accuracy: 0.7276
Epoch 72/100
402/402 [==============================] - 2s 6ms/step - loss: 0.5364 - accuracy: 0.7375 - val_loss: 0.5588 - val_accuracy: 0.7289
Epoch 73/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5361 - accuracy: 0.7389 - val_loss: 0.5601 - val_accuracy: 0.7284
Epoch 74/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5359 - accuracy: 0.7371 - val_loss: 0.5597 - val_accuracy: 0.7289
Epoch 75/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5363 - accuracy: 0.7369 - val_loss: 0.5594 - val_accuracy: 0.7287
Epoch 76/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5358 - accuracy: 0.7383 - val_loss: 0.5598 - val_accuracy: 0.7293
Epoch 77/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5360 - accuracy: 0.7374 - val_loss: 0.5589 - val_accuracy: 0.7283
Epoch 78/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5365 - accuracy: 0.7388 - val_loss: 0.5597 - val_accuracy: 0.7293
Epoch 79/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5358 - accuracy: 0.7372 - val_loss: 0.5593 - val_accuracy: 0.7280
Epoch 80/100
402/402 [==============================] - 2s 5ms/step - loss: 0.5362 - accuracy: 0.7377 - val_loss: 0.5596 - val_accuracy: 0.7288
Epoch 81/100
402/402 [==============================] - 2s 4ms/step - loss: 0.5358 - accuracy: 0.7385 - val_loss: 0.5609 - val_accuracy: 0.7290
Epoch 82/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5356 - accuracy: 0.7392 - val_loss: 0.5601 - val_accuracy: 0.7284
Epoch 83/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5355 - accuracy: 0.7394 - val_loss: 0.5592 - val_accuracy: 0.7291
Epoch 84/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5355 - accuracy: 0.7395 - val_loss: 0.5596 - val_accuracy: 0.7289
Epoch 85/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5358 - accuracy: 0.7388 - val_loss: 0.5598 - val_accuracy: 0.7278
Epoch 86/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5355 - accuracy: 0.7402 - val_loss: 0.5598 - val_accuracy: 0.7280
Epoch 87/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5353 - accuracy: 0.7380 - val_loss: 0.5597 - val_accuracy: 0.7278
Epoch 88/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5354 - accuracy: 0.7389 - val_loss: 0.5598 - val_accuracy: 0.7274
Epoch 89/100
402/402 [==============================] - 2s 6ms/step - loss: 0.5351 - accuracy: 0.7378 - val_loss: 0.5601 - val_accuracy: 0.7290
Epoch 90/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5354 - accuracy: 0.7374 - val_loss: 0.5606 - val_accuracy: 0.7275
Epoch 91/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5349 - accuracy: 0.7390 - val_loss: 0.5596 - val_accuracy: 0.7287
Epoch 92/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5354 - accuracy: 0.7385 - val_loss: 0.5594 - val_accuracy: 0.7280
Epoch 93/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5352 - accuracy: 0.7395 - val_loss: 0.5593 - val_accuracy: 0.7278
Epoch 94/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5350 - accuracy: 0.7392 - val_loss: 0.5597 - val_accuracy: 0.7283
Epoch 95/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5347 - accuracy: 0.7381 - val_loss: 0.5600 - val_accuracy: 0.7278
Epoch 96/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5352 - accuracy: 0.7393 - val_loss: 0.5597 - val_accuracy: 0.7283
Epoch 97/100
402/402 [==============================] - 2s 5ms/step - loss: 0.5346 - accuracy: 0.7405 - val_loss: 0.5609 - val_accuracy: 0.7288
Epoch 98/100
402/402 [==============================] - 1s 4ms/step - loss: 0.5353 - accuracy: 0.7402 - val_loss: 0.5592 - val_accuracy: 0.7274
Epoch 99/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5350 - accuracy: 0.7385 - val_loss: 0.5597 - val_accuracy: 0.7272
Epoch 100/100
402/402 [==============================] - 1s 3ms/step - loss: 0.5345 - accuracy: 0.7387 - val_loss: 0.5601 - val_accuracy: 0.7272

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5576 - accuracy: 0.7240 - 346ms/epoch - 1ms/step
Loss: 0.5575625896453857, Accuracy: 0.7239649891853333

In [16]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/Challenges/deep-learning-challenge/Model_1.h5')
files.download('/content/Challenges/deep-learning-challenge/Model_1.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(